#ifdef QQT_MAP_CITY
// QQT_MAP_CITY(identifier, num, description)
QQT_MAP_CITY(desert, 1, "沙漠")
QQT_MAP_CITY(snow, 2, "雪地")
QQT_MAP_CITY(town, 3, "中国城")
QQT_MAP_CITY(mine, 4, "矿洞")
QQT_MAP_CITY(water, 5, "水面")
QQT_MAP_CITY(field, 6, "野外")
QQT_MAP_CITY(bomb, 7, "足球")
QQT_MAP_CITY(bun, 8, "抢包山")
QQT_MAP_CITY(pig, 9, "功夫")
QQT_MAP_CITY(treasure, 10, "夺宝")
QQT_MAP_CITY(match, 11, "比武")
QQT_MAP_CITY(sculpture, 12, "英雄传说")
QQT_MAP_CITY(machine, 13, "机械世界")
QQT_MAP_CITY(box, 14, "推箱子")
QQT_MAP_CITY(practice, 15, "练习")
QQT_MAP_CITY(exploration, 16, "探险")
QQT_MAP_CITY(common, 17, "通用")
QQT_MAP_CITY(pve, 18, "PVE")
QQT_MAP_CITY(tank, 19, "糖客战")
#endif
