#ifdef QQT_GAME_MODE
// QQT_GAME_MODE(模式标识符, 编号, 中文字符串)
QQT_GAME_MODE(normal, 1, "普通")
QQT_GAME_MODE(bomb, 2, "足球")
QQT_GAME_MODE(bun, 3, "抢包山")
QQT_GAME_MODE(match, 4, "比武")
QQT_GAME_MODE(treasure, 5, "夺宝")
QQT_GAME_MODE(sculpture, 6, "英雄传说")
QQT_GAME_MODE(machine, 7, "机械世界")
QQT_GAME_MODE(box, 8, "推箱子")
QQT_GAME_MODE(practice, 9, "练习")
QQT_GAME_MODE(exploration, 10, "探险")
QQT_GAME_MODE(common, 11, "通用")
QQT_GAME_MODE(pve, 12, "PVE")
QQT_GAME_MODE(tank, 13, "糖客战")
#endif
